title: MultiEMO-ACL2023
description: This repository is the Pytorch implementation of ACL 2023 paper "MultiEMO: An Attention-Based Correlation-Aware Multimodal Fusion Framework for Emotion Recognition in Conversations". 
